const actions = {
    EESAPPROVAL_REQUEST: 'EESAPPROVAL_REQUEST',
    EESAPPROVAL_SUCCESS: 'EESAPPROVAL_SUCCESS',
    EESAPPROVAL_ERROR: 'EESAPPROVAL_ERROR',

    EESAPPROVAL_BUTTONAPPROVAL_REQUEST: 'EESAPPROVAL_BUTTONAPPROVAL_REQUEST',
    EESAPPROVAL_BUTTONAPPROVAL_SUCCESS: 'EESAPPROVAL_BUTTONAPPROVAL_SUCCESS',
    EESAPPROVAL_BUTTONAPPROVAL_ERROR: 'EESAPPROVAL_BUTTONAPPROVAL_ERROR',

    EESAPPROVAL_LIST_REQUEST: (payload) => ({
      type: actions.EESAPPROVAL_REQUEST,
      payload
    }),

    EESAPPROVAL_LIST_BUTTONAPPROVAL_REQUEST: (payload) => ({
      type: actions.EESAPPROVAL_BUTTONAPPROVAL_REQUEST,
      payload
    }),

  };
  export default actions;
  