const actions = {
    IATTENDPOLLINGCHOOSE_REQUEST: 'IATTENDPOLLINGCHOOSE_REQUEST',
    IATTENDPOLLINGCHOOSE_SUCCESS: 'IATTENDPOLLINGCHOOSE_SUCCESS',
    IATTENDPOLLINGCHOOSE_ERROR: 'IATTENDPOLLINGCHOOSE_ERROR',

    IATTENDPOLLINGCHOOSE_LIST_REQUEST: (payload) => ({
      type: actions.IATTENDPOLLINGCHOOSE_REQUEST,
      payload
    }),

  };
  export default actions;
  