const actions = {
    ETRAVELAPPROVAL_REQUEST: 'ETRAVELAPPROVAL_REQUEST',
    ETRAVELAPPROVAL_SUCCESS: 'ETRAVELAPPROVAL_SUCCESS',
    ETRAVELAPPROVAL_ERROR: 'ETRAVELAPPROVAL_ERROR',

    ETRAVELAPPROVAL_BUTTONAPPROVAL_REQUEST: 'ETRAVELAPPROVAL_BUTTONAPPROVAL_REQUEST',
    ETRAVELAPPROVAL_BUTTONAPPROVAL_SUCCESS: 'ETRAVELAPPROVAL_BUTTONAPPROVAL_SUCCESS',
    ETRAVELAPPROVAL_BUTTONAPPROVAL_ERROR: 'ETRAVELAPPROVAL_BUTTONAPPROVAL_ERROR',

    ETRAVELAPPROVAL_LIST_REQUEST: (payload) => ({
      type: actions.ETRAVELAPPROVAL_REQUEST,
      payload
    }),

    ETRAVELAPPROVAL_LIST_BUTTONAPPROVAL_REQUEST: (payload) => ({
      type: actions.ETRAVELAPPROVAL_BUTTONAPPROVAL_REQUEST,
      payload
    }),

  };
  export default actions;
  