const actions = {
    SPKLAPPROVAL_REQUEST: 'SPKLAPPROVAL_REQUEST',
    SPKLAPPROVAL_SUCCESS: 'SPKLAPPROVAL_SUCCESS',
    SPKLAPPROVAL_ERROR: 'SPKLAPPROVAL_ERROR',

    SPKLAPPROVAL_BUTTONAPPROVAL_REQUEST: 'SPKLAPPROVAL_BUTTONAPPROVAL_REQUEST',
    SPKLAPPROVAL_BUTTONAPPROVAL_SUCCESS: 'SPKLAPPROVAL_BUTTONAPPROVAL_SUCCESS',
    SPKLAPPROVAL_BUTTONAPPROVAL_ERROR: 'SPKLAPPROVAL_BUTTONAPPROVAL_ERROR',

    SPKLAPPROVAL_LIST_REQUEST: (payload) => ({
      type: actions.SPKLAPPROVAL_REQUEST,
      payload
    }),

    SPKLAPPROVAL_LIST_BUTTONAPPROVAL_REQUEST: (payload) => ({
      type: actions.SPKLAPPROVAL_BUTTONAPPROVAL_REQUEST,
      payload
    }),

  };
  export default actions;
  